# Generated by Django 5.2.4 on 2025-07-31 05:27

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional: CSS class or icon for display.', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('family', 'Family'), ('bachelor', 'Bachelor'), ('sublet', 'Sublet'), ('hostel', 'Hostel'), ('mess', 'Mess'), ('office', 'Office Space'), ('shop', 'Shop / Retail Space'), ('warehouse', 'Warehouse'), ('factory', 'Factory / Industrial Unit')], max_length=20)),
                ('property_type', models.CharField(choices=[('flat', 'Flat / Apartment'), ('floor', 'Floor'), ('room', 'Room'), ('seat', 'Seat (Hostel/Mess)'), ('house', 'House / Villa'), ('unit', 'Unit')], max_length=20)),
                ('available_from', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male only'), ('female', 'Female only'), ('any', 'Any')], default='any', max_length=10)),
                ('bedroom', models.PositiveSmallIntegerField(default=0)),
                ('bathroom', models.PositiveSmallIntegerField(default=0)),
                ('balcony', models.PositiveSmallIntegerField(default=0)),
                ('parking', models.PositiveSmallIntegerField(default=0)),
                ('others_room', models.PositiveSmallIntegerField(default=0)),
                ('floor_no', models.PositiveSmallIntegerField(default=0)),
                ('size', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('size_unit', models.CharField(blank=True, choices=[('sqft', 'Square feet'), ('sqm', 'Square meters')], default='sqft', max_length=10, null=True)),
                ('country', django_countries.fields.CountryField(default='BD', max_length=2)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('sub_area', models.CharField(max_length=100)),
                ('short_address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('pay_duration', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year'), ('contract', 'Contract')], default='month', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('property_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('all_amenities', models.ManyToManyField(related_name='properties', to='properties.amenity')),
                ('included_in_price_amenities', models.ManyToManyField(blank=True, related_name='included_in_properties', to='properties.amenity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.properties')),
            ],
        ),
    ]
